/**
 * Expo config plugin — Play Install Referrer native module (Android only).
 *
 * `android/` is gitignored in this project, so the native module can't be committed
 * directly. This plugin re-creates it on `expo prebuild`: it writes the Kotlin source,
 * adds the Install Referrer Gradle dependency, and registers the ReactPackage in
 * MainApplication. The JS side (src/install/*) reads it via NativeModules.AQInstallReferrer.
 *
 * Idempotent — safe to run repeatedly; each step no-ops if already applied.
 */
const { withAppBuildGradle, withMainApplication, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const ANDROID_PKG = "co.askquran.app";
const GRADLE_DEP = `implementation("com.android.installreferrer:installreferrer:2.2")`;

const MODULE_KT = `package co.askquran.app

import com.android.installreferrer.api.InstallReferrerClient
import com.android.installreferrer.api.InstallReferrerStateListener
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Reads the Google Play Install Referrer (the \`referrer\` string Play captures when
 * a user installs after tapping a Play link with \`&referrer=...\`). The JS layer
 * parses \`utm_volunteer=<code>\` out of it to attribute the install to a volunteer.
 *
 * \`getInstallReferrer\` resolves the raw referrer string (e.g. "utm_volunteer=ABC123")
 * or null when it is unavailable. It never rejects — attribution must never crash or
 * block app startup. (Generated by plugins/withInstallReferrer.js.)
 */
class InstallReferrerModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = NAME

  @ReactMethod
  fun getInstallReferrer(promise: Promise) {
    val settled = AtomicBoolean(false)
    fun resolveOnce(value: String?) {
      if (settled.compareAndSet(false, true)) promise.resolve(value)
    }
    try {
      val client = InstallReferrerClient.newBuilder(reactApplicationContext).build()
      client.startConnection(object : InstallReferrerStateListener {
        override fun onInstallReferrerSetupFinished(responseCode: Int) {
          try {
            if (responseCode == InstallReferrerClient.InstallReferrerResponse.OK) {
              resolveOnce(client.installReferrer.installReferrer)
            } else {
              resolveOnce(null)
            }
          } catch (t: Throwable) {
            resolveOnce(null)
          } finally {
            try { client.endConnection() } catch (_: Throwable) {}
          }
        }

        override fun onInstallReferrerServiceDisconnected() {
          resolveOnce(null)
        }
      })
    } catch (t: Throwable) {
      resolveOnce(null)
    }
  }

  companion object {
    const val NAME = "AQInstallReferrer"
  }
}
`;

const PACKAGE_KT = `package co.askquran.app

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Registers [InstallReferrerModule]. (Generated by plugins/withInstallReferrer.js.) */
class InstallReferrerPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(InstallReferrerModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;

/** Add the Install Referrer Gradle dependency (once). */
function withGradleDep(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes("com.android.installreferrer:installreferrer")) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /dependencies\s*\{/,
        (m) => `${m}\n    // Play Install Referrer — volunteer install attribution (withInstallReferrer plugin)\n    ${GRADLE_DEP}`,
      );
    }
    return cfg;
  });
}

/** Register InstallReferrerPackage in MainApplication.getPackages() (once). */
function withPackageRegistration(config) {
  return withMainApplication(config, (cfg) => {
    if (!cfg.modResults.contents.includes("InstallReferrerPackage()")) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /val packages = PackageList\(this\)\.packages/,
        (m) => `${m}\n            packages.add(InstallReferrerPackage()) // Play Install Referrer attribution`,
      );
    }
    return cfg;
  });
}

/** Write the Kotlin source files into the android project. */
function withKotlinSources(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app/src/main/java",
        ...ANDROID_PKG.split("."),
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "InstallReferrerModule.kt"), MODULE_KT);
      fs.writeFileSync(path.join(dir, "InstallReferrerPackage.kt"), PACKAGE_KT);
      return cfg;
    },
  ]);
}

module.exports = function withInstallReferrer(config) {
  config = withGradleDep(config);
  config = withPackageRegistration(config);
  config = withKotlinSources(config);
  return config;
};
